### ISSUE TITLE
Dataset link broken

### ISSUE THREAD

**Issue by qraleq** [ciampluca/Virtual-to-Real-Pedestrian-Detection#1]
Hi, it seems that the dataset download link is broken: `http://datino.isti.cnr.it/viped.zip`.
Can you please check?

**Comment by ciampluca** [comment]
Sorry for the delay. We have a problem on the server, we will solve it in a few days.

**Comment by Abduoit** [comment]
@ciampluca 
the link isn't fixed yet?
also, how to run an example of pre-trained model? with test.py file

**Comment by qraleq** [comment]
Hi @ciampluca, I'm following up on this. Were you able to fix the problem on the server?

**Comment by ciampluca** [comment]
Hi, sorry for the delay. Suddenly, we still have a problem with the server.
However, now you can find the dataset at [link](https://drive.google.com/drive/folders/1rL1f8Xr_7Zj9hAzEpz0SlGaY5as2NNX1?usp=sharing).
