### ISSUE TITLE
Can I get pedestrian ID?

### ISSUE THREAD

**Issue by myoh97** [ciampluca/Virtual-to-Real-Pedestrian-Detection#2]
Hi, Thanks for providing your dataset.

I want to use your dataset with pedestrian ID for research.
so, is there any solution to get pedestrian ID efficiently?
or, Do I have to just assign their ID by hand?

**Comment by ciampluca** [comment]
Hi, we are sorry but the dataset is suitable for pedestrian detection and not for tracking, so we did not provide the pedestrian IDs.
